### ISSUE TITLE
mirror grub

### ISSUE THREAD

**Issue by dyindude** [dyindude/ubuntu-zfs#22]
reference guide for ideas on how to do this

**Comment by dyindude** [comment]
for MBR:
dpkg-reconfigure grub-pc just runs grub-install on the selected devices, so we can handle this in ansible

**Comment by dyindude** [comment]
MBR already handles this:

```
- shell: "grub-install {{ item }}"
  with_items:
    - "{{ zfsprep_root_device_list }}"
  when: zfsprep_efi|default(false)|bool != true
```
